<a href="https://colab.research.google.com/github/prakash27/CSL522_ML/blob/master/assignments/Assignment_1_Python_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSB352: Data Mining 

**Instructor** : [Dr. Chandra Prakash]

* For more information visit the [class website](https://cprakash86.wordpress.com/csb352_s21/).


# LAB_1_Assignment : Introduction to Python 
**Due Date: 09-Jan-2021**


**Student Name: Yuvraj Singh Champawat**


**Roll Number: 181210064**

# Assignment Instructions


You must save your as Assignment_NO_Yourname

**Assignment 1 :** To complete assignment one, first you have to add your name and roll no in the Google Colab Instructions section below and print it. Perform the 10 task given in the assignment and submit it over Microsoft Team. 

Your source file will most likely end in **.pynb** if you are using a Jupyter notebook; however, it might also end in **.py** if you are using a Python script.



# Google CoLab Instructions

The following code ensures that Google CoLab is running the correct version of TensorFlow.



In [53]:
try:
    from google.colab import drive
    %tensorflow_version 2.x
    COLAB = True
    print("Hello World")
    print("Note: using Google CoLab")
    
except:
    print("Hello NITD")
    print("Note: not using Google CoLab")
    COLAB = False
    
# Print your name and Roll No. 
# Print the curent time 

print('\n\nMy name is Yuvraj Singh Champawat')
print('\nMy Roll Number is 181210064')

Hello World
Note: using Google CoLab


My name is Yuvraj Singh Champawat

My Roll Number is 181210064


**Exercise 1.** Create following list:

data = [2,34,23,16,56,45,34,26,78,56,1,16]

Write a function to count number of elements in a list . <br> 
Now delete the duplicate values and print the list in ascending order. 

In [54]:
#Write your code here
data = [2,34,23,16,56,45,34,26,78,56,1,16]

#Fucntion to count number of items in data list
def count_number_of_elements(data):
  count = 0
  for i in data:
    count = count+1
  print('Total elements present in given list are:  ' + str(count))

#Fucntion to count number of items in data list using len() function
def count_using_func (data):
  count = len(data)
  print('Total elements present in given list are:  ' + str(count))

count_number_of_elements(data)
count_using_func(data)

Total elements present in given list are:  12
Total elements present in given list are:  12


In [55]:
#Write your code here
data = [2,34,23,16,56,45,34,26,78,56,1,16]

import numpy as np

#Function to remove duplicate items and sort remaining items using extra list temp_list
def asc_order_no_duplicate(data):
  temp_list = []
  for item in data:
    if item not in temp_list:
      temp_list.append(item)
  temp_list.sort()
  print(temp_list)

#Function to remove duplicate items and sort remaining items using set() and list() functions
def task_using_func (data):
  temp_list = set(data)
  temp_list = list(temp_list)
  temp_list.sort()
  print(temp_list)

#Function to remove duplicate items and sort remaining items using Numpy unique() and tolist() functions
def task_using_numpy (data):
  temp_list = np.unique(data).tolist()
  temp_list.sort()
  print(temp_list)
  

asc_order_no_duplicate(data)
task_using_func(data)
task_using_numpy(data)

[1, 2, 16, 23, 26, 34, 45, 56, 78]
[1, 2, 16, 23, 26, 34, 45, 56, 78]
[1, 2, 16, 23, 26, 34, 45, 56, 78]


**Exercise 2:** Take five numbers as input from the user and save into a list. Find the maximum of the list and sort the data in descending order.

In [57]:
#Write your code here

data = []

for i in range(5):
  item = input('Enter ' + str(i+1) + ' number ')
  data.append(int(item))

#max element using max() function
print('\nMaximum element in list is ', max(data))

#Sorting elements of data in descending order
data.sort(reverse = True)
print(data)

Enter 1 number 1
Enter 2 number 4
Enter 3 number 2
Enter 4 number 5
Enter 5 number 3

Maximum element in list is  5
[5, 4, 3, 2, 1]


**Exercise 4:**

(i) Generate two arrays A1 and A2 of size 5 X 4 and 3 X 4 respectively using np.random()

(ii) Join them and make an array A3 of 8 X 4. Now append random numbers ranging between from 0 to 5 to make the fourth array A4 of size 10 X 10. 

(iii) Print all the arrays and their transpose ( Transpose of 'A' can be obtained by 'A.T') 

In [37]:
#Write your code here

A1 = np.random.random((5, 4))
A2 = np.random.random((3, 4))

print('A1 : ', A1)
print('\nA2 : ', A2)

A3 = np.concatenate((A1, A2), axis = 0)
print('\nA3 : ', A3)

A4 = np.append(A3, np.random.randint(0, 5, size = (8, 6)), axis = 1)
A4 = np.append(A4, np.random.randint(0, 5, size = (2, 10)), axis = 0)
print('\nA4 : ', A4)

print('\n Transpose of A1 : ', A1.transpose())
print('\n Transpose of A2 : ', A2.transpose())
print('\n Transpose of A3 : ', A3.transpose())
print('\n Transpose of A4 : ', A4.transpose())

A1 :  [[0.64466984 0.24340802 0.24671065 0.2249329 ]
 [0.02467587 0.33071847 0.26854963 0.69749059]
 [0.53785131 0.46586109 0.04314584 0.9966054 ]
 [0.0229113  0.4087229  0.18380234 0.31124747]
 [0.65996295 0.19209877 0.37600593 0.14146899]]

A2 :  [[0.17152175 0.65272499 0.94441682 0.73083932]
 [0.07481601 0.89068717 0.04127738 0.95849568]
 [0.82710421 0.91709828 0.73336725 0.73043279]]

A3 :  [[0.64466984 0.24340802 0.24671065 0.2249329 ]
 [0.02467587 0.33071847 0.26854963 0.69749059]
 [0.53785131 0.46586109 0.04314584 0.9966054 ]
 [0.0229113  0.4087229  0.18380234 0.31124747]
 [0.65996295 0.19209877 0.37600593 0.14146899]
 [0.17152175 0.65272499 0.94441682 0.73083932]
 [0.07481601 0.89068717 0.04127738 0.95849568]
 [0.82710421 0.91709828 0.73336725 0.73043279]]

A4 :  [[0.64466984 0.24340802 0.24671065 0.2249329  3.         4.
  4.         0.         0.         3.        ]
 [0.02467587 0.33071847 0.26854963 0.69749059 4.         2.
  4.         2.         0.         2.        ]
 [0.

**Exercise 5: Create two dictionaries.** 

The first dictionary 'name' will contain first name(key) of a person and its hash value(value). 
The Second will contain hash value(key) and mobile no(value). 


i) Add 5 entries.

ii) Delete two entries by taking the input from user as the first name.

ii) Add two entries by taking the input as the first name and mobile no. 

Hint: You can use remainder ( %) to obtain hash value. 

In [45]:
#Write your code here

name = {'Raj' : 1, 'Avi' : 2, 'Dev' : 3, 'Yuvi' : 4, 'Veer' : 5}
mobile = {1 : 12345, 2 : 23456, 3 : 34567, 4 : 45678, 5 : 56789}

print('Key Value pairs of name dictionary')
for item, value in name.items():
  print(item, value)

print('\n\n Key Value pairs of mobile dictionary')
for item, value in mobile.items():
  print(item, value)

item_del = input('\n Enter name to delete from dictionary :  ')
value_del = name[item_del]
del name[item_del]
del mobile[value_del]

item_del = input('\n Enter name to delete from dictionary :  ')
value_del = name[item_del]
del name[item_del]
del mobile[value_del]

item_add = input('\n Enter name to add from dictionary :  ')
value_add = input('\n Enter mobile number to add from dictionary :  ')
hash_val = int(value_add) % 100

name[item_add] = hash_val
mobile[hash_val] = value_add

item_add = input('\n Enter name to add from dictionary :  ')
value_add = input('\n Enter mobile number to add from dictionary :  ')
hash_val = int(value_add) % 100

name[item_add] = hash_val
mobile[hash_val] = value_add

print('\n\n Key Value pairs of name dictionary')
for item, value in name.items():
  print(item, value)

print('\n\n Key Value pairs of mobile dictionary')
for item, value in mobile.items():
  print(item, value)


Key Value pairs of name dictionary
Raj 1
Avi 2
Dev 3
Yuvi 4
Veer 5


 Key Value pairs of mobile dictionary
1 12345
2 23456
3 34567
4 45678
5 56789

 Enter name to delete from dictionary :  Raj

 Enter name to delete from dictionary :  Dev

 Enter name to add from dictionary :  Shagun

 Enter mobile number to add from dictionary :  23415

 Enter name to add from dictionary :  Ashu

 Enter mobile number to add from dictionary :  34521


 Key Value pairs of name dictionary
Avi 2
Yuvi 4
Veer 5
Shagun 15
Ashu 21


 Key Value pairs of mobile dictionary
2 23456
4 45678
5 56789
15 23415
21 34521


# PART 2: Introduction to NumPy    


**Exercise 6:** Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [58]:
#Write your code here

x = np.array([3, 5, 1, 4, 7])
y = np.array([2, 5, 4, 8, 2])

print("Original numbers:")
print(x)
print(y)

print("\n\nComparison - greater")
print(np.greater(x, y))

print("\n\nComparison - greater_equal")
print(np.greater_equal(x, y))

print("\n\nComparison - less")
print(np.less(x, y))

print("\n\nComparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5 1 4 7]
[2 5 4 8 2]


Comparison - greater
[ True False False False  True]


Comparison - greater_equal
[ True  True False False  True]


Comparison - less
[False False  True  True False]


Comparison - less_equal
[False  True  True  True False]


**Exercise 7:** Write a NumPy program to create an array with the values 100, 71, 113, 1050 and determine the size of the memory occupied by the array.

In [59]:
#Write your code here

x = np.array([100, 71, 113, 1050])
print("Size of the array: ", x.size) 
  
print("\nMemory size of one array element in bytes: ", x.itemsize) 
  
print("\nMemory size of numpy array in bytes:", x.size * x.itemsize)

Size of the array:  4

Memory size of one array element in bytes:  8

Memory size of numpy array in bytes: 32


**Exercise 8:** Write a NumPy program to get the powers ( x ^ 3 ) of an array values element-wise


Expected Output:
Original array
[1 2 3 4 5 ]
Output array: 
[ 1 8 27 64 125 ]

In [48]:
#Write your code here

x = np.array([1, 2, 3, 4, 5])
y = np.power(x, 3)
print(y)

[  1   8  27  64 125]


**Exercise 9:** Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.
Sample Output:
Original array:
[-1.3, -1.15, -0.1, 0.12, 1.7, 0.9, 1.1]

In [49]:
#Write your code here

x = np.array([-1.3, -1.15, -0.1, 0.12, 1.7, 0.9, 1.1])

a = np.floor(x)
b = np.ceil(x)
c = np.trunc(x)

print(a)
print(b)
print(c)

[-2. -2. -1.  0.  1.  0.  1.]
[-1. -1. -0.  1.  2.  1.  2.]
[-1. -1. -0.  0.  1.  0.  1.]


**Exercise 10:** Write a program in python to display prime numbers from x to y (here x and y are user given values).

In [51]:
#Write your code here

x = input('Enter x : ')
y = input('Enter y : ')

for num in range(int(x),int(y) + 1):  
   if num > 1:  
       for i in range(2,num):  
           if (num % i) == 0:  
               break  
       else:  
           print(num)  

Enter x : 1
Enter y : 10
2
3
5
7


# Observation \ Comments 

In [ ]:
#Write your observation\ Learning here

# 1. Various function related to List data structure of Python
# 2. Various function and concept of key-value pair related to Dictionary data structure of Python
# 3. Various function and operations related to NumPy library of Python
# 4. Function of Python

## Hint : 

Reference Book to learn python: https://anandology.com/python-practice-book/getting-started.html