# CSB352: Data Mining LAB
### Instructor : [Dr. Chandra Prakash]

## LAB 5: Data Pre-Processing

In [284]:
!pip install sklearn

You should consider upgrading via the 'c:\users\beeta\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [285]:
import numpy as np
import pandas as pd

In [286]:
# Read the Dataset
data_actuals=pd.read_csv('data/actuals.csv')
data_schedules=pd.read_csv('data/schedules.csv')
data_drones=pd.read_csv('data/drones.csv')
data_services=pd.read_csv('data/services.csv')
data_stations=pd.read_csv('data/stations.csv')

In [287]:
# Show the top 5 rows
data_actuals.head()

actual_arrival_datetime actual_departure_datetime  \
0        2050-07-01 05:06          2050-07-01 06:00   
1        2050-07-01 06:19          2050-07-01 07:00   
2        2050-07-01 07:09          2050-07-01 08:00   
3        2050-07-01 08:21          2050-07-01 09:00   
4        2050-07-01 09:09          2050-07-01 10:00   

   actual_fuel_consumption_gm_per_mile  actual_windspeed_kts  \
0                                56.12                     0   
1                               168.31                     0   
2                                77.31                     0   
3                               164.24                     0   
4                                69.68                     0   

   arrival_delay_seconds service_id station    station_call_id  
0                      2       JP_0   Iwade  JP_0_205007010506  
1                      5       JP_0  Komono  JP_0_205007010619  
2                      2       JP_0    Toba  JP_0_205007010709  
3                      6       JP_0    Gero  JP_0_205007010821  
4                      3       JP_0     Ina  JP_0_205007010909

In [288]:
# Show the top 5 rows
data_schedules.head()

forecast_windspeed_kts scheduled_arrival_datetime  \
0                       4           2050-07-01 05:06   
1                       7           2050-07-01 06:19   
2                       6           2050-07-01 07:09   
3                       8           2050-07-01 08:21   
4                      13           2050-07-01 09:09   

  scheduled_departure_datetime service_id station    station_call_id  
0             2050-07-01 06:00       JP_0   Iwade  JP_0_205007010506  
1             2050-07-01 07:00       JP_0  Komono  JP_0_205007010619  
2             2050-07-01 08:00       JP_0    Toba  JP_0_205007010709  
3             2050-07-01 09:00       JP_0    Gero  JP_0_205007010821  
4             2050-07-01 10:00       JP_0     Ina  JP_0_205007010909

In [289]:
data_drones.head()

capacity_persons  drone_id  fuel_consumption_gm_per_mile      manufacturer  \
0               114   971-LGB                          1.87         Sharp Ltd   
1               438   ZTG 357                          5.10  Freeman-Garrison   
2               493   I55 1AC                          0.79         Perez Inc   
3               154  XUW-2971                          2.84         Sharp Ltd   
4                59     564AL                          0.76    Greene-Beasley   

   max_altitude_ft  max_capacity_fuel_gm  min_capacity_fuel_gm  \
0             8000                  3740                     1   
1             7000                 10200                     1   
2             4000                  1580                     1   
3             9000                  2840                     1   
4            10000                  1520                     1   

   operating_speed_mph  optimal_altitude_ft service_id  
0                  266                 1000       JP_0  
1                  216                 1000       DZ_0  
2                  149                 2000       DE_1  
3                  291                 1000       US_0  
4                  188                 1000       JP_2

### Merging Data

In [290]:
# Check the merge command help
#data_drones.merge?

In [291]:
final_data = data_schedules.merge(data_drones,on='service_id')

In [292]:
final_data.head()

forecast_windspeed_kts scheduled_arrival_datetime  \
0                       4           2050-07-01 05:06   
1                       7           2050-07-01 06:19   
2                       6           2050-07-01 07:09   
3                       8           2050-07-01 08:21   
4                      13           2050-07-01 09:09   

  scheduled_departure_datetime service_id station    station_call_id  \
0             2050-07-01 06:00       JP_0   Iwade  JP_0_205007010506   
1             2050-07-01 07:00       JP_0  Komono  JP_0_205007010619   
2             2050-07-01 08:00       JP_0    Toba  JP_0_205007010709   
3             2050-07-01 09:00       JP_0    Gero  JP_0_205007010821   
4             2050-07-01 10:00       JP_0     Ina  JP_0_205007010909   

   capacity_persons drone_id  fuel_consumption_gm_per_mile manufacturer  \
0               114  971-LGB                          1.87    Sharp Ltd   
1               114  971-LGB                          1.87    Sharp Ltd   
2               114  971-LGB                          1.87    Sharp Ltd   
3               114  971-LGB                          1.87    Sharp Ltd   
4               114  971-LGB                          1.87    Sharp Ltd   

   max_altitude_ft  max_capacity_fuel_gm  min_capacity_fuel_gm  \
0             8000                  3740                     1   
1             8000                  3740                     1   
2             8000                  3740                     1   
3             8000                  3740                     1   
4             8000                  3740                     1   

   operating_speed_mph  optimal_altitude_ft  
0                  266                 1000  
1                  266                 1000  
2                  266                 1000  
3                  266                 1000  
4                  266                 1000

### Drop a column/row

In [293]:
# Checking the drop command:
final_data.drop?

In [294]:
clm_to_drop = ['scheduled_arrival_datetime','scheduled_departure_datetime','service_id','station','manufacturer','drone_id']

In [295]:
final_data.drop(columns=clm_to_drop,inplace=True)
# Those values were dropped and the changes were made in the original data frame since inplace was True.
final_data.head()

forecast_windspeed_kts    station_call_id  capacity_persons  \
0                       4  JP_0_205007010506               114   
1                       7  JP_0_205007010619               114   
2                       6  JP_0_205007010709               114   
3                       8  JP_0_205007010821               114   
4                      13  JP_0_205007010909               114   

   fuel_consumption_gm_per_mile  max_altitude_ft  max_capacity_fuel_gm  \
0                          1.87             8000                  3740   
1                          1.87             8000                  3740   
2                          1.87             8000                  3740   
3                          1.87             8000                  3740   
4                          1.87             8000                  3740   

   min_capacity_fuel_gm  operating_speed_mph  optimal_altitude_ft  
0                     1                  266                 1000  
1                     1                  266                 1000  
2                     1                  266                 1000  
3                     1                  266                 1000  
4                     1                  266                 1000

In [296]:
 # Drop Rows by index label station_call_id
index_labels = ["	JP_0_205007010506", "JP_0_205007010619"]
final_data.drop(final_data[final_data.station_call_id == "JP_0_205007010506"].index, inplace=True)

In [297]:
final_data.head()

forecast_windspeed_kts    station_call_id  capacity_persons  \
1                       7  JP_0_205007010619               114   
2                       6  JP_0_205007010709               114   
3                       8  JP_0_205007010821               114   
4                      13  JP_0_205007010909               114   
5                      13  JP_0_205007011013               114   

   fuel_consumption_gm_per_mile  max_altitude_ft  max_capacity_fuel_gm  \
1                          1.87             8000                  3740   
2                          1.87             8000                  3740   
3                          1.87             8000                  3740   
4                          1.87             8000                  3740   
5                          1.87             8000                  3740   

   min_capacity_fuel_gm  operating_speed_mph  optimal_altitude_ft  
1                     1                  266                 1000  
2                     1                  266                 1000  
3                     1                  266                 1000  
4                     1                  266                 1000  
5                     1                  266                 1000

In [298]:
# Display the final_data and size [ Row , Col]
final_data.info

<bound method DataFrame.info of        forecast_windspeed_kts       station_call_id  capacity_persons  \
1                           7     JP_0_205007010619               114   
2                           6     JP_0_205007010709               114   
3                           8     JP_0_205007010821               114   
4                          13     JP_0_205007010909               114   
5                          13     JP_0_205007011013               114   
...                       ...                   ...               ...   
12489                       1  World_3_205007300754              1066   
12490                       1  World_3_205007301936              1066   
12491                       0  World_3_205007310454              1066   
12492                       2  World_3_205007311854              1066   
12493                       6  World_3_205008010636              1066   

       fuel_consumption_gm_per_mile  max_altitude_ft  max_capacity_fuel_gm  \
1            

In [299]:
final_data

forecast_windspeed_kts       station_call_id  capacity_persons  \
1                           7     JP_0_205007010619               114   
2                           6     JP_0_205007010709               114   
3                           8     JP_0_205007010821               114   
4                          13     JP_0_205007010909               114   
5                          13     JP_0_205007011013               114   
...                       ...                   ...               ...   
12489                       1  World_3_205007300754              1066   
12490                       1  World_3_205007301936              1066   
12491                       0  World_3_205007310454              1066   
12492                       2  World_3_205007311854              1066   
12493                       6  World_3_205008010636              1066   

       fuel_consumption_gm_per_mile  max_altitude_ft  max_capacity_fuel_gm  \
1                              1.87             8000                  3740   
2                              1.87             8000                  3740   
3                              1.87             8000                  3740   
4                              1.87             8000                  3740   
5                              1.87             8000                  3740   
...                             ...              ...                   ...   
12489                         17.86             4000                 17860   
12490                         17.86             4000                 17860   
12491                         17.86             4000                 17860   
12492                         17.86             4000                 17860   
12493                         17.86             4000                 17860   

       min_capacity_fuel_gm  operating_speed_mph  optimal_altitude_ft  
1                         1                  266                 1000  
2                         1                  266                 1000  
3                         1                  266                 1000  
4                         1                  266                 1000  
5                         1                  266                 1000  
...                     ...                  ...                  ...  
12489                     1                  620                 1000  
12490                     1                  620                 1000  
12491                     1                  620                 1000  
12492                     1                  620                 1000  
12493                     1                  620                 1000  

[12493 rows x 9 columns]

### Divide DATA into Training and Testing

In [300]:
traning_data = final_data.merge(data_actuals[['arrival_delay_seconds','station_call_id']],on='station_call_id')

In [301]:
test_data = final_data[~final_data['station_call_id'].isin(traning_data['station_call_id'].to_list())]

- The tilde (~) operator is a bitwise not operator (inverses all the boolean conditions
- isin() (is in) method helps us to selecting rows with having particular value in a particular column

In [302]:
# Display the traning_data
traning_data

forecast_windspeed_kts       station_call_id  capacity_persons  \
0                          7     JP_0_205007010619               114   
1                          6     JP_0_205007010709               114   
2                          8     JP_0_205007010821               114   
3                         13     JP_0_205007010909               114   
4                         13     JP_0_205007011013               114   
...                      ...                   ...               ...   
9918                       0  World_3_205007232154              1066   
9919                       0  World_3_205007241154              1066   
9920                       0  World_3_205007242336              1066   
9921                       1  World_3_205007250854              1066   
9922                       0  World_3_205007252254              1066   

      fuel_consumption_gm_per_mile  max_altitude_ft  max_capacity_fuel_gm  \
0                             1.87             8000                  3740   
1                             1.87             8000                  3740   
2                             1.87             8000                  3740   
3                             1.87             8000                  3740   
4                             1.87             8000                  3740   
...                            ...              ...                   ...   
9918                         17.86             4000                 17860   
9919                         17.86             4000                 17860   
9920                         17.86             4000                 17860   
9921                         17.86             4000                 17860   
9922                         17.86             4000                 17860   

      min_capacity_fuel_gm  operating_speed_mph  optimal_altitude_ft  \
0                        1                  266                 1000   
1                        1                  266                 1000   
2                        1                  266                 1000   
3                        1                  266                 1000   
4                        1                  266                 1000   
...                    ...                  ...                  ...   
9918                     1                  620                 1000   
9919                     1                  620                 1000   
9920                     1                  620                 1000   
9921                     1                  620                 1000   
9922                     1                  620                 1000   

      arrival_delay_seconds  
0                         5  
1                         2  
2                         6  
3                         3  
4                         4  
...                     ...  
9918                    596  
9919                    686  
9920                    657  
9921                    596  
9922                    686  

[9923 rows x 10 columns]

In [303]:
# Display the test_data
test_data

forecast_windspeed_kts       station_call_id  capacity_persons  \
15                         10     JP_0_205007012308               114   
28                          2     JP_0_205007021819               114   
145                        19     JP_0_205007090619               114   
273                        11     JP_0_205007160821               114   
422                        20     JP_0_205007241603               114   
...                       ...                   ...               ...   
12489                       1  World_3_205007300754              1066   
12490                       1  World_3_205007301936              1066   
12491                       0  World_3_205007310454              1066   
12492                       2  World_3_205007311854              1066   
12493                       6  World_3_205008010636              1066   

       fuel_consumption_gm_per_mile  max_altitude_ft  max_capacity_fuel_gm  \
15                             1.87             8000                  3740   
28                             1.87             8000                  3740   
145                            1.87             8000                  3740   
273                            1.87             8000                  3740   
422                            1.87             8000                  3740   
...                             ...              ...                   ...   
12489                         17.86             4000                 17860   
12490                         17.86             4000                 17860   
12491                         17.86             4000                 17860   
12492                         17.86             4000                 17860   
12493                         17.86             4000                 17860   

       min_capacity_fuel_gm  operating_speed_mph  optimal_altitude_ft  
15                        1                  266                 1000  
28                        1                  266                 1000  
145                       1                  266                 1000  
273                       1                  266                 1000  
422                       1                  266                 1000  
...                     ...                  ...                  ...  
12489                     1                  620                 1000  
12490                     1                  620                 1000  
12491                     1                  620                 1000  
12492                     1                  620                 1000  
12493                     1                  620                 1000  

[2570 rows x 9 columns]

In [304]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [305]:
# Dropping station_call_id from training_data and test_data:

traning_data.drop(columns=['station_call_id'], inplace=True)
test_data.drop(columns=['station_call_id'], inplace=True)

c:\users\beeta\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py:4305: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [306]:
traning_data.head()

forecast_windspeed_kts  capacity_persons  fuel_consumption_gm_per_mile  \
0                       7               114                          1.87   
1                       6               114                          1.87   
2                       8               114                          1.87   
3                      13               114                          1.87   
4                      13               114                          1.87   

   max_altitude_ft  max_capacity_fuel_gm  min_capacity_fuel_gm  \
0             8000                  3740                     1   
1             8000                  3740                     1   
2             8000                  3740                     1   
3             8000                  3740                     1   
4             8000                  3740                     1   

   operating_speed_mph  optimal_altitude_ft  arrival_delay_seconds  
0                  266                 1000                      5  
1                  266                 1000                      2  
2                  266                 1000                      6  
3                  266                 1000                      3  
4                  266                 1000                      4

In [307]:
test_data.head()

forecast_windspeed_kts  capacity_persons  fuel_consumption_gm_per_mile  \
15                       10               114                          1.87   
28                        2               114                          1.87   
145                      19               114                          1.87   
273                      11               114                          1.87   
422                      20               114                          1.87   

     max_altitude_ft  max_capacity_fuel_gm  min_capacity_fuel_gm  \
15              8000                  3740                     1   
28              8000                  3740                     1   
145             8000                  3740                     1   
273             8000                  3740                     1   
422             8000                  3740                     1   

     operating_speed_mph  optimal_altitude_ft  
15                   266                 1000  
28                   266                 1000  
145                  266                 1000  
273                  266                 1000  
422                  266                 1000

In [308]:
features = list(traning_data.columns)

In [309]:
# Displaying the features:

features

['forecast_windspeed_kts',
 'capacity_persons',
 'fuel_consumption_gm_per_mile',
 'max_altitude_ft',
 'max_capacity_fuel_gm',
 'min_capacity_fuel_gm',
 'operating_speed_mph',
 'optimal_altitude_ft',
 'arrival_delay_seconds']

In [310]:
# Remove the arrival_delay_seconds object (or column) from the list:

features.remove('arrival_delay_seconds')

In [311]:
# Displaying the features:

features

['forecast_windspeed_kts',
 'capacity_persons',
 'fuel_consumption_gm_per_mile',
 'max_altitude_ft',
 'max_capacity_fuel_gm',
 'min_capacity_fuel_gm',
 'operating_speed_mph',
 'optimal_altitude_ft']

In [312]:
trainX, trainY = traning_data[features].values, traning_data['arrival_delay_seconds'].values
print("Train X: ", trainX)
print("Train Y: ", trainY)

Train X:  [[7.000e+00 1.140e+02 1.870e+00 ... 1.000e+00 2.660e+02 1.000e+03]
 [6.000e+00 1.140e+02 1.870e+00 ... 1.000e+00 2.660e+02 1.000e+03]
 [8.000e+00 1.140e+02 1.870e+00 ... 1.000e+00 2.660e+02 1.000e+03]
 ...
 [0.000e+00 1.066e+03 1.786e+01 ... 1.000e+00 6.200e+02 1.000e+03]
 [1.000e+00 1.066e+03 1.786e+01 ... 1.000e+00 6.200e+02 1.000e+03]
 [0.000e+00 1.066e+03 1.786e+01 ... 1.000e+00 6.200e+02 1.000e+03]]
Train Y:  [  5   2   6 ... 657 596 686]


In [313]:
testX = test_data.values
testX

array([[1.000e+01, 1.140e+02, 1.870e+00, ..., 1.000e+00, 2.660e+02,
        1.000e+03],
       [2.000e+00, 1.140e+02, 1.870e+00, ..., 1.000e+00, 2.660e+02,
        1.000e+03],
       [1.900e+01, 1.140e+02, 1.870e+00, ..., 1.000e+00, 2.660e+02,
        1.000e+03],
       ...,
       [0.000e+00, 1.066e+03, 1.786e+01, ..., 1.000e+00, 6.200e+02,
        1.000e+03],
       [2.000e+00, 1.066e+03, 1.786e+01, ..., 1.000e+00, 6.200e+02,
        1.000e+03],
       [6.000e+00, 1.066e+03, 1.786e+01, ..., 1.000e+00, 6.200e+02,
        1.000e+03]])

In [314]:
trainY

array([  5,   2,   6, ..., 657, 596, 686], dtype=int64)

In [315]:
trainX.shape, trainY.shape, testX.shape

((9923, 8), (9923,), (2570, 8))

## Normalization

- Need of Normalization 
- Type of Normalization 

- Min-Max Normalization:

z= (x-min)/max-min 


- Standard Normalization :  Z Normalization(Standardization):

z=x-x(mean)/standared  deviation 


- Mean or Normal Mean 

**Observation:** Normalization means transforming the data, namely converting the source data in to another format that allows processing data effectively. The main purpose of data normalization is to minimize or even exclude duplicated data.

Types of normalization: 

1. min-max normalization

2. Z-normalization

3. Decimal scaling method of normalization

In [316]:
StandardScaler?

In [317]:
scaler = StandardScaler()

In [318]:
scaler.fit(trainX)

StandardScaler()

In [319]:
scaler.transform?

In [320]:
trainX_norm = scaler.transform(trainX)
testX_norm = scaler.transform(testX)

In [321]:
print("TrainX after normalization: ", trainX_norm)
print("TestX after normalization: ", testX_norm)

TrainX after normalization:  [[-0.79410107 -0.90517577 -0.77526799 ...  0.          0.39996595
  -0.82109853]
 [-0.84231425 -0.90517577 -0.77526799 ...  0.          0.39996595
  -0.82109853]
 [-0.7458879  -0.90517577 -0.77526799 ...  0.          0.39996595
  -0.82109853]
 ...
 [-1.1315933   2.94316652  5.62216258 ...  0.          3.00770579
  -0.82109853]
 [-1.08338012  2.94316652  5.62216258 ...  0.          3.00770579
  -0.82109853]
 [-1.1315933   2.94316652  5.62216258 ...  0.          3.00770579
  -0.82109853]]
TestX after normalization:  [[-0.64946154 -0.90517577 -0.77526799 ...  0.          0.39996595
  -0.82109853]
 [-1.03516695 -0.90517577 -0.77526799 ...  0.          0.39996595
  -0.82109853]
 [-0.21554297 -0.90517577 -0.77526799 ...  0.          0.39996595
  -0.82109853]
 ...
 [-1.1315933   2.94316652  5.62216258 ...  0.          3.00770579
  -0.82109853]
 [-1.03516695  2.94316652  5.62216258 ...  0.          3.00770579
  -0.82109853]
 [-0.84231425  2.94316652  5.62216258 ...

In [322]:
trainX.max(), trainX.min(), trainX.mean()

(28280.0, 0.0, 2008.0710114128794)

In [323]:
trainX_norm.max(),trainX_norm.min(),trainX_norm.mean()

(6.617686620938104, -1.4181416914193756, 1.3605071026344758e-17)

## Label Encoding

#### DATA 
    S.No   Country	Age	 Salary

        0   India   44     72000
        1      US   34     65000
        2   Japan   46     98000
        3      US   35     45000
        4   Japan   23     34000

In [324]:
df=pd.read_csv("./data/Salary.csv")

In [325]:
df

Country  Age  Salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000

In [326]:
df.info

<bound method DataFrame.info of   Country  Age  Salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000>

In [327]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()   # labelEncoder
df['Country']= label_encoder.fit_transform(df['Country']) 
df.head()

Country  Age  Salary
0        0   44   72000
1        2   34   65000
2        1   46   98000
3        2   35   45000
4        1   23   34000

In [328]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(df.Country.values.reshape(-1,1)).toarray()
dfOneHot = pd.DataFrame(X, columns = ["Country_"+str(int(i)) for i in range(df.shape[1])]) 
df = pd.concat([df, dfOneHot], axis=1)
df=df.drop(['Country'], axis=1) 
df.head()

Age  Salary  Country_0  Country_1  Country_2
0   44   72000        1.0        0.0        0.0
1   34   65000        0.0        0.0        1.0
2   46   98000        0.0        1.0        0.0
3   35   45000        0.0        0.0        1.0
4   23   34000        0.0        1.0        0.0

## Missing Values

In [329]:
dataset = pd.read_csv('data/pima-indians-diabetes1.csv', header=None)

In [330]:
dataset.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [331]:
dataset.describe()

0           1           2           3           4           5  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

                6           7           8  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [332]:
num_missing = (dataset[[1,2,3,4,5,7]] == 0).sum()

In [333]:
num_missing

1      5
2     35
3    227
4    374
5     11
7      0
dtype: int64

In [334]:
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0, np.nan)
dataset.isnull().sum()

0      0
1      5
2     35
3    227
4    374
5     11
6      0
7      0
8      0
dtype: int64

In [335]:
dataset.head()

0      1     2     3      4     5      6   7  8
0  6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1  1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2  8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3  1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4  0  137.0  40.0  35.0  168.0  43.1  2.288  33  1

### Remove rows

In [336]:
print(dataset.shape)
dataset.dropna(inplace=True)
print(dataset.shape)

(768, 9)
(392, 9)


### Replace missing value

Fill missing with mean

In [337]:
from sklearn.impute import SimpleImputer

In [338]:
dataset = pd.read_csv('data/pima-indians-diabetes.csv', header=None)
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0, np.nan)
values = dataset.values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
transformed_values = imputer.fit_transform(values)
print(f'Missing: {np.isnan(transformed_values).sum()}' )

Missing: 0


In [339]:
dataset.head()

0      1     2     3      4     5      6   7  8
0  6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1  1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2  8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3  1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4  0  137.0  40.0  35.0  168.0  43.1  2.288  33  1

In [340]:
transformed_values[0]

array([  6.        , 148.        ,  72.        ,  35.        ,
       155.54822335,  33.6       ,   0.627     ,  50.        ,
         1.        ])

In [341]:
# Fill missing with most frequent value 

dataset = pd.read_csv('data/pima-indians-diabetes.csv', header=None)
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0, np.nan)
values = dataset.values
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
transformed_values = imputer.fit_transform(values)
print(f'Missing: {np.isnan(transformed_values).sum()}')

Missing: 0


In [342]:
transformed_values

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

## Class Imbalance -  SMOTE

https://imbalanced-learn.readthedocs.io/en/stable/over_sampling.html

In [343]:
!pip install imblearn --user 

You should consider upgrading via the 'c:\users\beeta\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [344]:
import imblearn
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE # doctest: +NORMALIZE_WHITESPACE

In [345]:
X, y = make_classification(n_classes=2, class_sep=2,
weights=[0.1, 0.9], n_informative=3, n_redundant=1, flip_y=0,
n_features=20, n_clusters_per_class=1, n_samples=1000, random_state=10)

In [346]:
print('Original dataset shape %s' % Counter(y))

Original dataset shape Counter({1: 900, 0: 100})


In [347]:
sm = SMOTE(random_state=42)

In [348]:
X_res, y_res = sm.fit_resample(X, y)

In [349]:
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({0: 900, 1: 900})
